baseURL = 'https://api-platform.com/docs/'
languageCode = 'en-us'
title = 'Getting Started With API Platform: Create Your API and Your Jamstack Site'
theme = "api-platform"
disablePathToLower = true

[markup]
  [markup.highlight]
    # anchorLineNos = false
    # codeFences = true
    # guessSyntax = false
    # hl_Lines = ''
    # hl_inline = false
    # lineAnchors = ''
    # lineNoStart = 1
    # lineNos = false
    # lineNumbersInTable = true
    noClasses = false
    # noHl = false
    style = 'github'
    # tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
